[package]
name = "mobile"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
jni = "0.21.1"
serde = "1.0.219"
serde_json = "1.0.140"
tracing.workspace = true
ui.workspace = true

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]

