[package]
name = "mobile"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
dioxus-motion = { version = "0.3.1", default-features = false }
serde = "1.0.219"
serde_json = "1.0.140"
tracing.workspace = true
ui.workspace = true

[features]
default = ["mobile"]
mobile = ["dioxus/mobile", "dioxus-motion/desktop", "dioxus-motion/transitions"]

